# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: genius-ye
email: genius-ye@126.com
description: >
  我就是我，一种不一样的烟火……
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
url_work: "/work"
url_travel: "/travel"
paginate:	8 # The number of posts to show per page on your homepage

name: 'genius-ye'
bio: >
  I am me, a different kind of fireworks ... ...
author_image: "/assets/images/author.jpg"
twitter_username: genius-ye
github_username:  genius-ye

# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true
  # 给 Kramdown 传递值为 “GFM” 的 input 选项，从而启用 Github 扩展的 Markdown 语法
  input: GFM

gems:
  - jekyll-paginate
